include theos/makefiles/common.mk

LIBRARY_NAME = libAppHeads
libAppHeads_FILES = $(wildcard *.m)
libAppHeads_FRAMEWORKS = UIKit
libAppHeads_PRIVATE_FRAMEWORKS = SpringBoardUI
libAppHeads_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/library.mk
