include theos/makefiles/common.mk

BUNDLE_NAME = AppHeadsFS
AppHeadsFS_FILES = Switch.x
AppHeadsFS_FRAMEWORKS = UIKit
AppHeadsFS_LDFLAGS = -L$(LIB_DIR)
AppHeadsFS_LIBRARIES = flipswitch AppHeads
AppHeadsFS_INSTALL_PATH = /Library/Switches
AppHeadsFS_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk