include theos/makefiles/common.mk

TWEAK_NAME = ActiHeads
ActiHeads_FILES = ActiHeads.mm
ActiHeads_FRAMEWORKS = UIKit
ActiHeads_LDFLAGS = -L$(LIB_DIR)
ActiHeads_LIBRARIES = activator AppHeads flipswitch

include $(THEOS_MAKE_PATH)/tweak.mk

